# Generated by Django 5.0.3 on 2024-03-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Destination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("discription", models.TextField(max_length=200)),
                ("price", models.IntegerField()),
                ("offer", models.BooleanField(default=False)),
            ],
        ),
    ]
